# Generated by Django 5.2.1 on 2025-05-21 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("En cours", "En cours"),
                            ("En design", "Design en cours"),
                            ("Développement", "Développement"),
                            ("Terminé", "Terminé"),
                        ],
                        default="En attente",
                        max_length=50,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
