# Generated by Django 5.2.1 on 2025-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_projet"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="message_client",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projet",
            name="nom",
            field=models.CharField(max_length=100),
        ),
    ]
